apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-parking-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-parking-frontend
  template:
    metadata:
      labels:
        app: smart-parking-frontend
    spec:
      containers:
        - name: frontend
          image: sgal88/frontend:1.2
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: smart-parking-frontend
spec:
  selector:
    app: smart-parking-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
